In [1]:
import tensorflow as tf

hello_constant = tf.constant("Hello World")

with tf.Session() as sess:
    output = sess.run(hello_constant)
    print(output)

b'Hello World'


In [2]:
A = tf.constant(1234)
print(A)

B = tf.constant([123,4,5,6])
print(B)

C = tf.constant([[1,2],[3,4]])
print(C)

Tensor("Const_1:0", shape=(), dtype=int32)
Tensor("Const_2:0", shape=(4,), dtype=int32)
Tensor("Const_3:0", shape=(2, 2), dtype=int32)


In [3]:
with tf.Session() as sess:
    o = sess.run(A)
    print(o)
    o = sess.run(B)
    print(o)
    o = sess.run(C)
    print(o)

1234
[123   4   5   6]
[[1 2]
 [3 4]]


In [6]:
X = tf.placeholder(tf.string)
with tf.Session() as sess:
    o = sess.run(X,feed_dict={X:"Manh Le"})
    print(o)
    

Manh Le


In [9]:
Y = tf.placeholder(tf.float32)
Z = tf.placeholder(tf.int32)
with tf.Session() as sess:
    o = sess.run(X,feed_dict={X:'Test',Z:123})
    print(o)
    o = sess.run(Z,feed_dict={Z:1234})
    print(o)

Test
1234


In [16]:
Q = tf.add(2,3)
W = tf.subtract(2.0,3)
E = tf.multiply(1, 10)

In [17]:
with tf.Session() as sess:
    o = sess.run(Q)
    print(o)
    o = sess.run(W)
    print(o)
    o = sess.run(E)
    print(o)

5
-1.0
10


In [18]:
v = tf.Variable(5)

with tf.Session() as sess:
    sess.run(init)

In [29]:
n_features = 5
n_labels = 3

weights = tf.Variable(tf.truncated_normal((n_features,n_labels)))

print(weights)
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    o = sess.run(weights)
    print(o)


bias =  tf.Variable(tf.zeros(n_labels))

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    o = sess.run(bias)
    print(o)


<tf.Variable 'Variable_9:0' shape=(5, 3) dtype=float32_ref>
[[-0.9818547  -0.8179221   1.2418176 ]
 [ 0.53863573 -0.6385577   0.97618276]
 [-0.7630397   0.33219892  1.4704081 ]
 [ 0.91939193  0.5354188  -0.19832405]
 [-0.289371   -0.32291028  0.29197627]]
[0. 0. 0.]
